# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# google-ID: 'UA-112060364-1'

menu:
- {name: 'درباره من', path: 'menu', url: 'about.html'}
- {name: 'آرشیو مطالب', path: 'menu', url: 'writing.html'}
- {name: 'تماس با من', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/algo-school'}
# - {icon: 'twitter', link: 'https://twitter.com/paululele'}
# - {icon: 'linkedin', link: 'http://www.linkedin.com/in/lenpaul/'}
# - {icon: 'envelope', link: 'mailto:l.nguyen.paul@gmail.com'}
# - {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}
# - {icon: 'aparat', link: 'https://www.aparat.com/algo_school'} TODO

# Customize site text
pagination:
  next_page: 'جدید تر'
  previous_page: 'قدیمی تر'

sharing_button_prompt: 'با خیال راحت به اشتراک بگذارید'

related_posts: 'شاید این ها را نیز دوست داشته باشید :'

post_date_prefix: 'نوشته شده در '
